### ISSUE TITLE
Update meta info

### ISSUE THREAD

**Issue by tangrufus** [ItinerisLtd/tiller-monorepo-circleci-orb#4]
- [ ] Update description in `/src`
- [ ] Update description in readme
- [x] Mention https://github.com/ItinerisLtd/tiller-circleci-orb in readme
- [ ] Mention file structure in readme
